jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: my_user
      password: my_password
      port: 5432
      dbname: my_db
      schema: public
      threads: 4
      keepalives_idle: 0
      sslmode: prefer
      search_path: public
